### ISSUE TITLE
can you share a sample settings json block for use with this module?

### ISSUE THREAD

**Issue by axfelix** [filehoarder/ep_password_change#13]
It's not totally clear to me how to set up file-based storage of the hash right now. Thanks!

**Comment by papeg** [comment]
for setting up filebased hash storage please refer to the readme of ep_hash_auth (https://github.com/ether/ep_hash_auth).
ep_password_change is just an extension to this plugin allowing you to change the hashes which are already on the file system

**Comment by papeg** [comment]
this plugin does not need any additional settings

**Comment by axfelix** [comment]
Yeah, sorry, should've clarified -- that other plugin's documentation didn't lead me to believe that the passwords would be configurable from the interface at all, I couldn't tell whether the value of `"hash": "b2112aa7399 ... b071ea5976"}` were supposed to be redundant with `[folder]/.hash` or whether you were only supposed to use one or the other, etc. I'd like to see what a working example of user-configurable passwords looks like!

**Comment by papeg** [comment]
you can only use one.. if you have a hash in settings.json and on filesystem for the same user then the one in the settings.json file is selected. this plugin allows you to change the password of the current user if the hash is stored on filesystem.
for usage just install the plugin and click "change password" on the main page.
hope this helps

**Comment by axfelix** [comment]
I don't understand what a `"users"` config block looks like in that case. You still have to declare non-admin users, right? You just don't have to provide any credentials for them when you're using this block?

```
  "ep_hash_auth": {
    "hash_typ": "sha512",
    "hash_dig": "hex",
    "hash_dir": "/var/etherpad/users",
    "hash_ext": "/.hash",
    "hash_adm": false
  },
```

**Comment by papeg** [comment]
if the users are all declared on the filesystem you dont need a users block in settings.json just a folder in "hash_dir" which is named after the user and a .hash file in there in which the hash is stored

**Comment by axfelix** [comment]
Wait, so it can create accounts based on the presence of a folder name in the hash directory? So in order to have one admin user with a hardcoded password and multiple regular users, you'd have one entry in the user block, one filesystem hash block, and a bunch of premade user folders?

I really think some documentation would be helpful... I'd be happy to help provide it if you can help me get this straight.

**Comment by papeg** [comment]
this plugin can only change a hash which is already on the filesystem. the hash has to be created and stored by hand with the commands provided in ep_hash_auth README.md. 
we want to create a plugin which enables admin users to create new users but we havent started yet

im not exactly sure how to create a admin user with hash based storage. this plugin can only change the password of a regular user

**Comment by axfelix** [comment]
Got it, thanks, that helps!

**Comment by papeg** [comment]
Youre welcome!
